[tool.poetry]
<<<<<<< HEAD
name = "unlearning-bench"
version = "0.1.0"
description = ""
authors = ["Roy Rinberg <royrinberg@gmail.com>"]

readme = "README.md"


packages = [
	{include = "unlearning"},

]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"
torch = "^2.2.1"
ipykernel = "^6.29.2"
matplotlib = "^3.8.3"
tqdm = "^4.66.2"
torchvision = "^0.17.1"
scikit-learn = "^1.4.1.post1"
pandas = "^2.2.1"

seaborn = "^0.13.2"
jupyter-black = "^0.3.4"


#traker = "^0.3.2"
#pickleshare = "^0.7.5"
#opacus = "^1.4.1"
#submitit = "^1.5.1"
#transformers = "^4.40.2"
#tiktoken = "^0.6.0"
=======
name = "data-unlearning-bench"
version = "0.1.0"
description = ""
authors = [
    "Roy Rinberg <royrinberg@gmail.com>", 
    "Pol Puigdemont Plana <polpuigdemont@gmail.com>
    ]

packages = [
    {include = "unlearning_bench"},
]

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.2.6"
torch = "^2.7.1"
ipykernel = "^6.29.5"
matplotlib = "^3.10.3"
tqdm = "^4.67.1"
torchvision = "^0.22.1"
pandas = "^2.3.0"
>>>>>>> MUGEN_workshop


[tool.poetry.group.dev.dependencies]
yapf = "^0.43.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
