results_dir: "path/to/output/files"
dataset: "CIFAR10"
forget_set_id: 5
unlearning_algo: "oracle_matching"  # choose unlearning algo name (e.g. `gradient_ascent`), according to `NAME_TO_ALGO` in unlearning.unlearning_algos.base_nn.py
unlearning_algo_kwargs:
  dataset: "CIFAR10"
  oracles_path: "path/to/oracles/for/specific/forget_set/"
  num_epochs: 13
  learning_rate: 5.e-4
  retain_learning_rate: 2.e-4
  batch_size: 256
  optimizer: "adam"
  retain_data_amount: 20.
run_direct_eval: False  # this is the expensive eval - 
save_unlearned_margins: True
N_models_for_direct: 100
reorder_logit_classes: False
